name: first workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: list files in the directory
              run: ls

            - name: read
              run: cat README.md
