name: multi job workflow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Run shell script
              run: chmod +x ./hello.sh && ./hello.sh

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Run shell script
              run: cat README.md
